  services:
    users-service:
      container_name: users-service
      image: users-service:${NODE_ENV}
      build: 
        target: ${NODE_ENV}
        context: .
      ports:
        - ${APP_PORT}:${APP_PORT}
      networks:
        - pokemon-network
      volumes:
        - redis-users:/data
        - mongo-users:/data/db

      depends_on: 
        - redis
        - mongo

      healthcheck:
        test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:${APP_PORT}/health"]
        start_period: "3s"

    redis: 
      image: redis:alpine
      ports:
        - 6379:6379
      networks:
        - pokemon-network

    mongo: 
      image: "mongo:latest"
      ports: 
        - 27017:27017
      networks:
        - pokemon-network
        
  networks:
    pokemon-network:
      name: pokemon-network

  volumes:
    redis-users:
    mongo-users:
