  services:
    pokemon-service:
      container_name: pokemon-service
      image: pokemon-service:${NODE_ENV}
      build: 
        target: ${NODE_ENV}
        context: .
      ports:
        - ${APP_PORT}:${APP_PORT}
      networks:
        - pokemon-network
      volumes:
        - redis-pokemon:/data
      depends_on: 
        - redis
      healthcheck:
        test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:${APP_PORT}/health"]
        start_period: "3s"

    redis: 
      image: redis:alpine
      ports:
        - 6380:6379
      networks:
        - pokemon-network
    
  networks:
    pokemon-network:
      name: pokemon-network

  volumes:
    redis-pokemon:
